### ISSUE TITLE
bug: TypeScript build failure — MidiEffectChain.tsx references non-existent store methods

### ISSUE THREAD

**Issue by ChuxiJ** [ace-step/ACE-Step-DAW#264]
## Summary
`npm run build` (tsc) fails with 7 errors in `src/components/mixer/MidiEffectChain.tsx`. The component references store methods/properties that do not exist:

**ProjectState (projectStore):**
- `updateMidiEffect` — does not exist (lines 53, 95, 149)
- `toggleMidiEffect` — does not exist (line 201)
- `reorderMidiEffect` — does not exist (did you mean `removeMidiEffect`?) (line 317)

**UIState (uiStore):**
- `openMidiEffectChainTrackId` — does not exist (did you mean `openEffectChainTrackId`?) (line 318)
- `setOpenMidiEffectChainTrackId` — does not exist (did you mean `setOpenEffectChainTrackId`?) (line 321)

## Impact
- **Build is completely broken** on `main` (commit f30bd06)
- All E2E tests fail (dev server cannot start)
- Introduced in commit 23e5413

## Steps to reproduce
```bash
git checkout main && npm run build
```

## Expected
Build succeeds.

## Actual
```
src/components/mixer/MidiEffectChain.tsx(53,53): error TS2339: Property updateMidiEffect does not exist on type ProjectState.
... (7 total errors)
```
